version: "3.9"
   
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  back:
    build:
      context: ./lib_catalog
      dockerfile: Dockerfile
    command: ["/bin/bash", "-c", "python manage.py migrate && exec python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db